path:
  raw_dir: "data/raw"
  processed_dir: "data/processed"
  models_dir: "models/"
  output_dir: "reports/figures"
  checkpoint_dir: "checkpoints"
  
general:
  seed: 42
  presence_cat: ["notumor", "tumor"] 
  classes: ["notumor", "glioma", "meningioma", "pituitary"]
  debug: False
  
data_loading:
  kaggle_dataset: "masoudnickparvar/brain-tumor-mri-dataset"
  
data_preprocessing:
  img_size: 260 
  split: [0.7, 0.30]  # train - validation -> test data are always in a separated directory
  low_clip: -1.3045
  high_clip: 3.0091
  
model:
  batch_size: 32
  freeze_backbone: True
  project_name: "BrainTumorMRI"
  model_type: "DenseNet121"
  two_head: True
  mask_tumor_type_loss: True
  data_augmentation: True
  unfreeze_layer: "conv5_block"
  nb_img_shap: 10
  epochs: 80